// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xxhhnxdgwlxymkpwibps.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh4aGhueGRnd2x4eW1rcHdpYnBzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyNDY0MTUsImV4cCI6MjA2MzgyMjQxNX0.qdDPvbjzrfomv2ghD9MsNtGQ8y84r8_Z-2clOgKjc-I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);